Artillery Sidewinder X2
SoftFever/BambuStudio-SoftFever pull request #84
Opened 2022-12-31 18:50 UTC by GP3D84

2023-01-02 06:30 UTC, SoftFever requested changes

2023-01-02 06:30 UTC, SoftFever commented on resources/profiles/Artillery.json
> +            "name": "Anker Generic ABS",
Could you rename it to Artillery?

2023-01-02 06:30 UTC, SoftFever commented
Thank you for the PR.
Could you take a look at my comment?

2023-01-02 12:23 UTC, GP3D84 commented on resources/profiles/Artillery.json
> +            "name": "Anker Generic ABS",
Fixed. Thanks

2023-01-03 02:02 UTC, SoftFever approved these changes

2023-01-03 02:02 UTC, SoftFever commented
Merged.
Thank you.

2023-01-03 02:02 UTC, merged